"""Display-only English translations for legacy German simulation labels."""

from __future__ import annotations


DISPLAY_TRANSLATIONS: dict[str, str] = {
    "Großbritannien": "United Kingdom",
    "GroÃŸbritannien": "United Kingdom",
    "GroÃƒÅ¸britannien": "United Kingdom",
    "Automobil": "Automotive",
    "Chemie": "Chemicals",
    "Öl und Gas": "Oil & Gas",
    "Ã–l und Gas": "Oil & Gas",
    "Stromerzeuger": "Power Utilities",
    "Maschinenbau": "Industrial Machinery",
    "Telekommunikation": "Telecommunications",
    "Einzelhandel": "Retail",
    "Konsumgüter": "Consumer Goods",
    "KonsumgÃ¼ter": "Consumer Goods",
    "Finanzen": "Financials",
    "Edelmetallförderer": "Precious Metals Mining",
    "Edelmetallf\u00f6rderer": "Precious Metals Mining",
    "Gesundheit": "Healthcare",
    "Technologie": "Technology",
    "Immobilien": "Real Estate",
    "Transport und Logistik": "Transportation & Logistics",
    "Verteidigung": "Defense",
    "Landwirtschaft": "Agriculture",
    "Rohstoffförderer": "Raw Materials Producers",
    "Rohstofff\u00f6rderer": "Raw Materials Producers",
    "Energieträger": "Energy Commodities",
    "Energietraeger": "Energy Commodities",
    "Industriemetalle und Mineralische Rohstoffe": "Industrial Metals & Minerals",
    "Edel- und Spezialmetalle": "Precious & Specialty Metals",
    "Seltene Erden": "Rare Earths",
    "Landwirtschaftliche Primärgüter": "Agricultural Primary Goods",
    "Landwirtschaftliche Prim\u00e4rg\u00fcter": "Agricultural Primary Goods",
    "Tierische Güter": "Animal Products",
    "Tierische G\u00fcter": "Animal Products",
    "Energieprodukte": "Energy Products",
    "Metall- und Werkstoffprodukte": "Metals & Materials",
    "Chemieprodukte": "Chemical Products",
    "Elektronik- und Technologieprodukte": "Electronics & Technology Products",
    "Maschinen und Investitionsgüter": "Machinery & Capital Goods",
    "Maschinen und Investitionsg\u00fcter": "Machinery & Capital Goods",
    "Endprodukte und Dienstleistungen": "Final Goods & Services",
    "Erdöl": "Crude Oil",
    "Erdgas": "Natural Gas",
    "Kohle": "Coal",
    "Eisenerz": "Iron Ore",
    "Kupfer": "Copper",
    "Kobalt": "Cobalt",
    "Silizium": "Silicon",
    "Phosphat": "Phosphate",
    "Salz": "Salt",
    "Kalkstein": "Limestone",
    "Stein und Kies": "Stone & Gravel",
    "Silber": "Silver",
    "Platin": "Platinum",
    "Getreide": "Grain",
    "Ölsaaten und Pflanzenöle": "Oilseeds & Vegetable Oils",
    "\u00d6lsaaten und Pflanzen\u00f6le": "Oilseeds & Vegetable Oils",
    "Kaffee": "Coffee",
    "Kakao": "Cocoa",
    "Zucker": "Sugar",
    "Holz": "Timber",
    "Baumwolle": "Cotton",
    "Naturkautschuk": "Natural Rubber",
    "Fleisch": "Meat",
    "Fisch": "Fish",
    "Elektrizität": "Electricity",
    "Elektrizit\u00e4t": "Electricity",
    "Raffinierte Treibstoffe": "Refined Fuels",
    "Industriewärme": "Industrial Heat",
    "Industriew\u00e4rme": "Industrial Heat",
    "Stahl": "Steel",
    "Kupferprodukte": "Copper Products",
    "Speziallegierungen": "Specialty Alloys",
    "Glas": "Glass",
    "Zement": "Cement",
    "Baustoffe": "Construction Materials",
    "Verpackung": "Packaging",
    "Chemische Grundstoffe": "Basic Chemicals",
    "Kunststoffe": "Plastics",
    "Dünger": "Fertilizers",
    "D\u00fcnger": "Fertilizers",
    "Industriegase": "Industrial Gases",
    "Synthetischer Kautschuk": "Synthetic Rubber",
    "Pharmawirkstoffe": "Active Pharmaceutical Ingredients",
    "Farben und Beschichtungen": "Paints & Coatings",
    "Reinigungsprodukte": "Cleaning Products",
    "Halbleiter": "Semiconductors",
    "Elektronikkomponenten": "Electronic Components",
    "Batterien": "Batteries",
    "Kommunikationstechnik": "Communications Equipment",
    "Computerhardware": "Computer Hardware",
    "Software und digitale Dienste": "Software & Digital Services",
    "Industriemaschinen": "Industrial Machinery",
    "Förderanlagen": "Mining & Extraction Equipment",
    "F\u00f6rderanlagen": "Mining & Extraction Equipment",
    "Landwirtschaftsmaschinen": "Agricultural Machinery",
    "Baumaschinen": "Construction Machinery",
    "Fabrikausrüstung": "Factory Equipment",
    "Fabrikausr\u00fcstung": "Factory Equipment",
    "Energieanlagen": "Power Generation Equipment",
    "Logistikausrüstung": "Logistics Equipment",
    "Logistikausr\u00fcstung": "Logistics Equipment",
    "Fahrzeuge": "Vehicles",
    "Fahrzeugteile": "Vehicle Parts",
    "Reifen": "Tires",
    "Verarbeitete Lebensmittel": "Processed Foods",
    "Getränke": "Beverages",
    "Getr\u00e4nke": "Beverages",
    "Textilien": "Textiles",
    "Bekleidung": "Apparel",
    "Haushaltswaren": "Household Goods",
    "Luxusgüter": "Luxury Goods",
    "Luxusg\u00fcter": "Luxury Goods",
    "Körperpflegeprodukte": "Personal Care Products",
    "K\u00f6rperpflegeprodukte": "Personal Care Products",
    "Medikamente": "Pharmaceuticals",
    "Medizintechnik": "Medical Technology",
    "Gesundheitsdienstleistungen": "Healthcare Services",
    "Unterhaltungselektronik": "Consumer Electronics",
    "Unternehmenshardware": "Enterprise Hardware",
    "Softwareprodukte": "Software Products",
    "Cloud- und Rechenzentrumsdienste": "Cloud & Data Center Services",
    "Digitale Plattformen": "Digital Platforms",
    "Wohngebäude, Gewerbeimmobilien, Vermietungsleistungen": "Residential & Commercial Real Estate Services",
    "Wohngeb\u00e4ude, Gewerbeimmobilien, Vermietungsleistungen": "Residential & Commercial Real Estate Services",
    "Frachttransport": "Freight Transportation",
    "Mobilfunkdienste": "Mobile Network Services",
    "Festnetzdienste": "Fixed-Line Services",
    "Datendienste": "Data Services",
    "Kredite": "Credit Services",
    "Versicherungsleistungen": "Insurance Services",
    "Vermögensverwaltung": "Asset Management",
    "Verm\u00f6gensverwaltung": "Asset Management",
    "Zahlungsdienste": "Payment Services",
    "Kleinwaffen": "Small Arms",
    "Haushalte": "Households",
    "alle Branchen": "all industries",
    "alle produzierenden Branchen": "all manufacturing industries",
    "produzierende Branchen": "manufacturing industries",
    "Metallverarbeitung": "Metals Processing",
    "Industrie": "Industry",
    "Elektronik": "Electronics",
    "Edelstahl": "Stainless Steel",
    "Länderfonds": "Country Fund",
    "Land": "Country",
}


def display_label(value: object) -> str:
    """Translate a player-facing label while leaving unknown values unchanged."""

    text = str(value)
    return DISPLAY_TRANSLATIONS.get(text, text)


def display_text(value: object) -> str:
    """Translate known German terms inside a longer player-facing string."""

    text = str(value)
    for source, target in sorted(DISPLAY_TRANSLATIONS.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(source, target)
    return text
