"""Tradable derivative product universe driven by existing market mechanics."""

from __future__ import annotations

import math
from datetime import datetime, timedelta
from types import ModuleType
from typing import Any

from kojakstreet.core.countries import COUNTRIES, RESERVE_CURRENCY
from kojakstreet.core.ohlc import append_ohlc_from_move

FUTURE_TENORS = (1, 3, 6)
OPTION_TENORS = (1, 3)
OPTION_MONEYNESS = (0.95, 1.0, 1.05)
YIELD_TENORS = (2, 5, 10, 30)
CDS_NOTIONAL = 10_000_000.0
CDS_RECOVERY_RATE = 0.40
CDS_CONTRACT_SCALE = 10_000.0
DERIVATIVE_MARKET_CAP = 100_000_000.0
EXPIRING_DERIVATIVE_CONTRACT_TYPES = {
    "Commodity Future",
    "Commodity Spread Future",
    "FX Forward",
    "Freight Future",
    "Inflation Swap",
    "Input-Cost Spread",
    "Yield Future",
}
CDS_CONTRACT_TYPES = {"Credit Default Swap", "Corporate Credit Default Swap"}
SPOT_SETTLED_DERIVATIVE_TYPES = {"Option", *CDS_CONTRACT_TYPES}


def derivative_allows_spot_trade(asset: dict[str, Any]) -> bool:
    return str(asset.get("instrument_type", "")) in SPOT_SETTLED_DERIVATIVE_TYPES


def derivative_allows_future_trade(asset: dict[str, Any]) -> bool:
    return str(asset.get("instrument_type", "")) in EXPIRING_DERIVATIVE_CONTRACT_TYPES


def derivative_use_case(asset: dict[str, Any]) -> str:
    instrument_type = str(asset.get("instrument_type", ""))
    if instrument_type == "Commodity Future":
        return "Locks or speculates on a future raw-material or processed-product price."
    if instrument_type == "Commodity Spread Future":
        return "Trades relative scarcity between two linked commodity or logistics markets."
    if instrument_type == "Freight Future":
        return "Hedges transport and shipping-rate pressure across global trade routes."
    if instrument_type == "Input-Cost Spread":
        return "Tracks the margin between a finished product and its weighted input basket."
    if instrument_type == "FX Forward":
        return "Hedges exchange-rate and interest-rate-differential exposure."
    if instrument_type == "Inflation Swap":
        return "Hedges unexpected inflation against a fixed inflation strike."
    if instrument_type == "Yield Future":
        return "Expresses or hedges interest-rate and yield-curve risk."
    if instrument_type == "Option":
        return "Buys convex upside or downside exposure with expiry settlement."
    if instrument_type in CDS_CONTRACT_TYPES:
        return "Buys credit protection against sovereign or corporate default."
    return "Derivative exposure driven by its referenced market."


def derivative_pricing_note(asset: dict[str, Any]) -> str:
    instrument_type = str(asset.get("instrument_type", ""))
    if instrument_type in CDS_CONTRACT_TYPES:
        scale = float(asset.get("contract_scale", CDS_CONTRACT_SCALE) or CDS_CONTRACT_SCALE)
        notional = float(asset.get("notional", CDS_NOTIONAL) or CDS_NOTIONAL)
        return (
            "Displayed price is a scaled protection-value indicator, not an equity-style quote "
            f"(notional {notional:,.0f}, scale {scale:,.0f})."
        )
    if instrument_type == "Option":
        return "Displayed price combines intrinsic value and simplified time value."
    if instrument_type in EXPIRING_DERIVATIVE_CONTRACT_TYPES:
        return "Displayed price is a simulation mark for futures-style long/short exposure."
    return "Displayed price is generated by the simulation model."


def ensure_financial_product_universe(daten: ModuleType, *, reset: bool = False) -> None:
    if reset or not hasattr(daten, "derivatives"):
        daten.derivatives = {}
    derivatives: dict[str, dict[str, Any]] = daten.derivatives
    if derivatives and getattr(daten, "derivative_universe_complete", False):
        return
    derivatives.clear()
    _add_commodity_futures(daten, derivatives)
    _add_cds_contracts(daten, derivatives)
    _add_corporate_cds_contracts(daten, derivatives)
    _add_options(daten, derivatives)
    _add_yield_futures(daten, derivatives)
    _add_fx_forwards(daten, derivatives)
    _add_inflation_swaps(daten, derivatives)
    _add_commodity_spread_futures(daten, derivatives)
    _add_input_cost_spreads(daten, derivatives)
    _add_freight_futures(daten, derivatives)
    daten.derivative_universe_complete = True


def update_financial_products(daten: ModuleType, zeit_str: str) -> None:
    ensure_financial_product_universe(daten)
    for ticker, product, instrument_type in _financial_product_runtimes(daten):
        old_price = float(product.get("kurs", 100.0))
        price = _price_product(daten, ticker, product, instrument_type)
        product["kurs"] = max(0.01, price)
        product["aenderung"] = ((product["kurs"] - old_price) / old_price * 100.0) if old_price > 0 else 0.0
        product["market_cap"] = float(product.get("open_interest", DERIVATIVE_MARKET_CAP))
        append_ohlc_from_move(product, old_price, product["kurs"], zeit_str, limit=1040)


def roll_expired_financial_products(daten: ModuleType) -> None:
    today = getattr(daten, "datum", None)
    if not isinstance(today, datetime):
        return
    for _ticker, product, instrument_type in _financial_product_runtimes(daten):
        expires_at = _parse_date(product.get("expires_at"))
        if expires_at is None or today < expires_at:
            continue
        if instrument_type == "Option":
            _reset_option_contract(daten, product)
        elif instrument_type == "Credit Default Swap":
            _reset_cds_contract(daten, product)


def _financial_product_runtimes(daten: ModuleType) -> list[tuple[str, dict[str, Any], str]]:
    derivatives = getattr(daten, "derivatives", {})
    signature = tuple((ticker, id(product), str(product.get("instrument_type", ""))) for ticker, product in derivatives.items())
    cache = getattr(daten, "_financial_product_runtime_cache", None)
    if isinstance(cache, dict) and cache.get("signature") == signature:
        return cache["products"]
    products = [
        (str(ticker), product, str(product.get("instrument_type", "")))
        for ticker, product in derivatives.items()
    ]
    daten._financial_product_runtime_cache = {"signature": signature, "products": products}
    return products


def _add_commodity_futures(daten: ModuleType, derivatives: dict[str, dict[str, Any]]) -> None:
    underlyings = list(getattr(daten, "rohstoffe", {}).items())[:24]
    products = list(getattr(daten, "processed_products", {}).items())[:18]
    for code, asset in [*underlyings, *products]:
        for tenor in FUTURE_TENORS:
            ticker = f"F{code}{tenor}M"[:8]
            derivatives[ticker] = _base_product(
                name=f"{asset.get('name', code)} {tenor}M Future",
                instrument_type="Commodity Future",
                underlying=str(code),
                tenor_months=tenor,
                region=RESERVE_CURRENCY,
                sector=str(asset.get("kategorie", asset.get("category", "Futures"))),
            )


def _add_cds_contracts(daten: ModuleType, derivatives: dict[str, dict[str, Any]]) -> None:
    for country in COUNTRIES:
        ticker = f"CDS{country.code}"
        product = _base_product(
            name=f"{country.name} 5Y Sovereign CDS",
            instrument_type="Credit Default Swap",
            underlying=country.name,
            tenor_months=60,
            notional=CDS_NOTIONAL,
            contract_scale=CDS_CONTRACT_SCALE,
            contract_size=CDS_NOTIONAL / CDS_CONTRACT_SCALE,
            recovery_rate=CDS_RECOVERY_RATE,
            region=country.name,
            sector="Sovereign Credit",
        )
        _reset_cds_contract(daten, product)
        derivatives[ticker] = product


def _add_corporate_cds_contracts(daten: ModuleType, derivatives: dict[str, dict[str, Any]]) -> None:
    for ticker, asset in list(getattr(daten, "aktien", {}).items())[:120]:
        symbol = f"CDX{ticker}"[:8]
        product = _base_product(
            name=f"{asset.get('name', ticker)} 5Y Corporate CDS",
            instrument_type="Corporate Credit Default Swap",
            underlying=str(ticker),
            underlying_type="Corporate",
            tenor_months=60,
            notional=CDS_NOTIONAL,
            contract_scale=CDS_CONTRACT_SCALE,
            contract_size=CDS_NOTIONAL / CDS_CONTRACT_SCALE,
            recovery_rate=0.35,
            region=str(asset.get("land", RESERVE_CURRENCY)),
            sector="Corporate Credit",
        )
        _reset_cds_contract(daten, product)
        derivatives[symbol] = product


def _add_options(daten: ModuleType, derivatives: dict[str, dict[str, Any]]) -> None:
    underlyings = []
    underlyings.extend((ticker, asset, "Index") for ticker, asset in list(getattr(daten, "indizes", {}).items())[:10])
    underlyings.extend((ticker, asset, "Commodity") for ticker, asset in list(getattr(daten, "rohstoffe", {}).items())[:8])
    for ticker, asset, asset_type in underlyings:
        for tenor in OPTION_TENORS:
            for moneyness in OPTION_MONEYNESS:
                for option_type in ("CALL", "PUT"):
                    strike_pct = round(moneyness * 100)
                    symbol = f"O{ticker[:3]}{option_type[0]}{strike_pct}{tenor}"
                    product = _base_product(
                        name=f"{asset.get('name', ticker)} {option_type.title()} {strike_pct}% {tenor}M",
                        instrument_type="Option",
                        underlying=str(ticker),
                        underlying_type=asset_type,
                        tenor_months=tenor,
                        option_type=option_type,
                        strike_moneyness=moneyness,
                        region=str(asset.get("land", asset.get("ziel", RESERVE_CURRENCY))),
                        sector=f"{asset_type} Options",
                    )
                    _reset_option_contract(daten, product)
                    derivatives[symbol] = product


def _add_yield_futures(daten: ModuleType, derivatives: dict[str, dict[str, Any]]) -> None:
    for country in COUNTRIES:
        for tenor in YIELD_TENORS:
            ticker = f"Y{country.code}{tenor}Y"
            derivatives[ticker] = _base_product(
                name=f"{country.name} {tenor}Y Yield Future",
                instrument_type="Yield Future",
                underlying=country.name,
                tenor_years=tenor,
                region=country.name,
                sector="Rates",
            )


def _add_fx_forwards(daten: ModuleType, derivatives: dict[str, dict[str, Any]]) -> None:
    currencies = [RESERVE_CURRENCY, *list(getattr(daten, "LAENDER", {}).keys())[:12]]
    pairs = [(RESERVE_CURRENCY, quote) for quote in currencies if quote != RESERVE_CURRENCY]
    pairs.extend((currencies[index], currencies[index + 1]) for index in range(1, len(currencies) - 1, 2))
    for base, quote in pairs:
        for tenor in FUTURE_TENORS:
            ticker = f"FX{_region_code(base)}{_region_code(quote)}{tenor}"[:8]
            derivatives[ticker] = _base_product(
                name=f"{_currency_label(base)}/{_currency_label(quote)} {tenor}M FX Forward",
                instrument_type="FX Forward",
                underlying=f"{base}/{quote}",
                base_currency=base,
                quote_currency=quote,
                tenor_months=tenor,
                region=quote,
                sector="FX Forwards",
            )


def _add_inflation_swaps(daten: ModuleType, derivatives: dict[str, dict[str, Any]]) -> None:
    for country in list(getattr(daten, "makro", {}))[:16]:
        for tenor in (1, 3, 5):
            ticker = f"INF{_region_code(country)}{tenor}"[:8]
            derivatives[ticker] = _base_product(
                name=f"{country} {tenor}Y Inflation Swap",
                instrument_type="Inflation Swap",
                underlying=country,
                tenor_years=tenor,
                fixed_rate=_expected_inflation(daten, country, tenor),
                region=country,
                sector="Inflation",
            )


def _add_commodity_spread_futures(daten: ModuleType, derivatives: dict[str, dict[str, Any]]) -> None:
    spreads = [
        ("CL", "FREIGHT", "Oil vs Freight"),
        ("XPT", "VEH", "Platinum vs Vehicles"),
        ("HG", "GRID", "Copper vs Grid Equipment"),
        ("FUEL", "AIRF", "Fuel vs Air Freight"),
    ]
    for long_code, short_code, name in spreads:
        if not _market_asset(daten, long_code) or not _market_asset(daten, short_code):
            continue
        for tenor in FUTURE_TENORS:
            ticker = f"SP{long_code[:2]}{short_code[:2]}{tenor}"[:8]
            derivatives[ticker] = _base_product(
                name=f"{name} {tenor}M Spread Future",
                instrument_type="Commodity Spread Future",
                long_leg=long_code,
                short_leg=short_code,
                tenor_months=tenor,
                region=RESERVE_CURRENCY,
                sector="Commodity Spreads",
            )


def _add_input_cost_spreads(daten: ModuleType, derivatives: dict[str, dict[str, Any]]) -> None:
    spread_specs = [
        ("AIRPL", "Aircraft Margin Spread"),
        ("SHIPB", "Shipbuilding Margin Spread"),
        ("TRAIN", "Rail Vehicle Margin Spread"),
    ]
    for output_code, name in spread_specs:
        if output_code not in getattr(daten, "processed_products", {}):
            continue
        for tenor in FUTURE_TENORS:
            ticker = f"IC{output_code[:4]}{tenor}"[:8]
            derivatives[ticker] = _base_product(
                name=f"{name} {tenor}M",
                instrument_type="Input-Cost Spread",
                underlying=output_code,
                output_code=output_code,
                tenor_months=tenor,
                region=RESERVE_CURRENCY,
                sector="Input-Cost Spreads",
            )


def _add_freight_futures(daten: ModuleType, derivatives: dict[str, dict[str, Any]]) -> None:
    for tenor in FUTURE_TENORS:
        ticker = f"FRGT{tenor}M"
        derivatives[ticker] = _base_product(
            name=f"Global Freight Rate {tenor}M Future",
            instrument_type="Freight Future",
            underlying="FREIGHT",
            tenor_months=tenor,
            region=RESERVE_CURRENCY,
            sector="Shipping & Freight",
        )


def _base_product(**values: Any) -> dict[str, Any]:
    product = {
        "kurs": 100.0,
        "historie": [(100.0, "01.01.1990", "")],
        "aenderung": 0.0,
        "market_cap": DERIVATIVE_MARKET_CAP,
        "open_interest": DERIVATIVE_MARKET_CAP,
        "typ": "Derivatives",
        "land": values.get("region", RESERVE_CURRENCY),
        "branche": values.get("sector", "Derivatives"),
    }
    product.update(values)
    product["pricing_note"] = derivative_pricing_note(product)
    return product


def _price_product(daten: ModuleType, ticker: str, product: dict[str, Any], instrument_type: str | None = None) -> float:
    instrument_type = str(product.get("instrument_type", "")) if instrument_type is None else instrument_type
    if instrument_type == "Commodity Future":
        return _commodity_future_price(daten, product)
    if instrument_type == "Credit Default Swap":
        return _cds_price(daten, product)
    if instrument_type == "Corporate Credit Default Swap":
        return _corporate_cds_price(daten, product)
    if instrument_type == "Option":
        return _option_price(daten, product)
    if instrument_type == "Yield Future":
        return _yield_future_price(daten, product)
    if instrument_type == "FX Forward":
        return _fx_forward_price(daten, product)
    if instrument_type == "Inflation Swap":
        return _inflation_swap_price(daten, product)
    if instrument_type == "Commodity Spread Future":
        return _commodity_spread_future_price(daten, product)
    if instrument_type == "Input-Cost Spread":
        return _input_cost_spread_price(daten, product)
    if instrument_type == "Freight Future":
        return _freight_future_price(daten, product)
    return float(product.get("kurs", 100.0))


def _commodity_future_price(daten: ModuleType, product: dict[str, Any]) -> float:
    underlying = str(product.get("underlying", ""))
    asset = getattr(daten, "rohstoffe", {}).get(underlying) or getattr(daten, "processed_products", {}).get(underlying, {})
    spot = float(asset.get("kurs", 100.0))
    tenor = float(product.get("tenor_months", 1))
    shortage = float(asset.get("shortage", 0.0))
    pressure = float(asset.get("pressure", 0.0))
    inventories = float(asset.get("inventories", asset.get("lagerbestand", 0.0)))
    storage = 0.0025 * tenor + max(0.0, inventories) * 0.00001
    scarcity = max(0.0, shortage + pressure) * tenor * 0.22
    carry = _global_rate(daten) * tenor / 12.0
    return spot * (1.0 + carry + storage - scarcity)


def _cds_price(daten: ModuleType, product: dict[str, Any]) -> float:
    country = str(product.get("underlying", ""))
    macro = getattr(daten, "makro", {}).get(country, {})
    default_probability = float(macro.get("default_probability", macro.get("default_prob", 0.02)))
    debt = float(macro.get("debt_to_gdp", 0.60))
    deficit = abs(float(macro.get("fiscal_deficit", 0.02)))
    spread = max(0.002, default_probability * 1.75 + max(0.0, debt - 0.6) * 0.025 + deficit * 0.35)
    product["spread"] = spread
    product["default_probability"] = default_probability
    product["recovery_rate"] = float(product.get("recovery_rate", CDS_RECOVERY_RATE))
    return spread * float(product.get("notional", CDS_NOTIONAL)) / CDS_CONTRACT_SCALE


def _corporate_cds_price(daten: ModuleType, product: dict[str, Any]) -> float:
    ticker = str(product.get("underlying", ""))
    asset = getattr(daten, "aktien", {}).get(ticker, {})
    rating_default = _rating_default_probability(str(asset.get("rating", "BBB")))
    default_probability = float(asset.get("default_probability", asset.get("default_prob", rating_default)))
    debt_ratio = float(asset.get("debt_to_market_cap", 0.20))
    fcf_margin = float(asset.get("fcf_margin", 0.08))
    cash = float(asset.get("cash_reserves", 0.0))
    revenue = max(1.0, float(asset.get("revenue", 1.0)))
    cash_buffer = cash / revenue
    spread = max(
        0.003,
        default_probability * 1.95
        + max(0.0, debt_ratio - 0.45) * 0.16
        + max(0.0, 0.04 - fcf_margin) * 1.2
        - min(0.018, cash_buffer * 0.030),
    )
    product["spread"] = spread
    product["default_probability"] = default_probability
    return spread * float(product.get("notional", CDS_NOTIONAL)) / CDS_CONTRACT_SCALE


def _option_price(daten: ModuleType, product: dict[str, Any]) -> float:
    underlying = str(product.get("underlying", ""))
    asset_type = str(product.get("underlying_type", ""))
    asset = _asset(daten, asset_type, underlying)
    spot = float(asset.get("kurs", 100.0))
    strike = float(product.get("strike_price", spot * float(product.get("strike_moneyness", 1.0))))
    tenor = max(1.0 / 365.0, _days_to_expiry(daten, product) / 365.0)
    volatility = _implied_volatility(daten, asset, asset_type)
    intrinsic = max(0.0, spot - strike) if product.get("option_type") == "CALL" else max(0.0, strike - spot)
    time_value = spot * volatility * math.sqrt(tenor) * 0.34
    product["intrinsic_value"] = intrinsic
    product["time_value"] = time_value
    return intrinsic + time_value


def _yield_future_price(daten: ModuleType, product: dict[str, Any]) -> float:
    country = str(product.get("underlying", ""))
    tenor = float(product.get("tenor_years", 10))
    macro = getattr(daten, "makro", {}).get(country, {})
    policy = float(macro.get("zins", 0.035))
    inflation = float(macro.get("inflation", 0.01))
    growth = float(macro.get("bip_prozent", 0.01))
    debt = float(macro.get("debt_to_gdp", 0.60))
    bond_market_yield = _government_bond_market_yield(daten, country, tenor)
    curve = (tenor / 30.0) * (inflation * 0.45 + max(0.0, debt - 0.55) * 0.025 - growth * 0.20)
    macro_yield = policy * (0.72 if tenor <= 2 else 0.45) + inflation * 0.55 + curve
    yield_rate = max(0.001, macro_yield * 0.60 + bond_market_yield * 0.40 if bond_market_yield else macro_yield)
    product["yield_rate"] = yield_rate
    product["bond_market_yield"] = bond_market_yield
    product["yield_curve_component"] = curve
    return max(1.0, 100.0 - yield_rate * 100.0 * min(12.0, tenor) / 2.8)


def _freight_future_price(daten: ModuleType, product: dict[str, Any]) -> float:
    freight = getattr(daten, "processed_products", {}).get("FREIGHT", {})
    spot = float(freight.get("kurs", 100.0))
    total_trade = 0.0
    for macro in getattr(daten, "makro", {}).values():
        total_trade += sum(float(value) for value in dict(macro.get("exports", {})).values())
        total_trade += sum(float(value) for value in dict(macro.get("imports", {})).values())
    energy = float(getattr(daten, "rohstoffe", {}).get("CL", {}).get("kurs", 100.0)) / 100.0
    tenor = float(product.get("tenor_months", 1))
    trade_pressure = min(0.45, total_trade / 300_000.0)
    return spot * (1.0 + trade_pressure + (energy - 1.0) * 0.18 + tenor * 0.003)


def _fx_forward_price(daten: ModuleType, product: dict[str, Any]) -> float:
    base = str(product.get("base_currency", RESERVE_CURRENCY))
    quote = str(product.get("quote_currency", RESERVE_CURRENCY))
    tenor = float(product.get("tenor_months", 1))
    spot = _currency_strength(daten, base) / _currency_strength(daten, quote)
    base_rate = _country_rate(daten, base)
    quote_rate = _country_rate(daten, quote)
    forward = spot * (1.0 + (base_rate - quote_rate) * tenor / 12.0)
    product["spot_rate"] = spot
    product["forward_rate"] = forward
    product["rate_differential"] = base_rate - quote_rate
    return max(1.0, 100.0 * forward / max(0.0001, spot))


def _inflation_swap_price(daten: ModuleType, product: dict[str, Any]) -> float:
    country = str(product.get("underlying", ""))
    tenor = float(product.get("tenor_years", 1))
    fixed_rate = float(product.get("fixed_rate", _expected_inflation(daten, country, tenor)))
    expected = _expected_inflation(daten, country, tenor)
    product["expected_inflation"] = expected
    product["fixed_rate"] = fixed_rate
    return max(1.0, 100.0 + (expected - fixed_rate) * 100.0 * min(5.0, tenor) * 4.0)


def _commodity_spread_future_price(daten: ModuleType, product: dict[str, Any]) -> float:
    long_asset = _market_asset(daten, str(product.get("long_leg", "")))
    short_asset = _market_asset(daten, str(product.get("short_leg", "")))
    long_price = float(long_asset.get("kurs", 100.0))
    short_price = float(short_asset.get("kurs", 100.0))
    tenor = float(product.get("tenor_months", 1))
    spread = (long_price / max(1.0, short_price)) - 1.0
    pressure = float(long_asset.get("shortage", 0.0)) - float(short_asset.get("shortage", 0.0))
    product["spread"] = spread
    product["spread_pressure"] = pressure
    return max(1.0, 100.0 * (1.0 + spread + pressure * 0.18 + tenor * 0.001))


def _input_cost_spread_price(daten: ModuleType, product: dict[str, Any]) -> float:
    output_code = str(product.get("output_code", ""))
    output = getattr(daten, "processed_products", {}).get(output_code, {})
    output_price = float(output.get("kurs", 100.0))
    input_cost = _weighted_input_cost(daten, output_code)
    margin = (output_price - input_cost) / max(1.0, output_price)
    shortage = float(output.get("shortage", 0.0))
    product["input_cost"] = input_cost
    product["margin_spread"] = margin
    return max(1.0, 100.0 * (1.0 + margin - shortage * 0.12))


def _global_rate(daten: ModuleType) -> float:
    rates = [float(macro.get("zins", 0.035)) for macro in getattr(daten, "makro", {}).values()]
    return sum(rates) / len(rates) if rates else 0.035


def _asset(daten: ModuleType, asset_type: str, ticker: str) -> dict[str, Any]:
    if asset_type == "Index":
        return getattr(daten, "indizes", {}).get(ticker, {})
    if asset_type == "Commodity":
        return getattr(daten, "rohstoffe", {}).get(ticker, {})
    return {}


def _reset_option_contract(daten: ModuleType, product: dict[str, Any]) -> None:
    asset = _asset(daten, str(product.get("underlying_type", "")), str(product.get("underlying", "")))
    spot = float(asset.get("kurs", 100.0))
    product["issue_date"] = _current_date(daten).strftime("%Y-%m-%d")
    product["expires_at"] = _expiry_date(daten, float(product.get("tenor_months", 1))).strftime("%Y-%m-%d")
    product["strike_price"] = spot * float(product.get("strike_moneyness", 1.0))
    product["underlying_at_issue"] = spot


def _reset_cds_contract(daten: ModuleType, product: dict[str, Any]) -> None:
    product["issue_date"] = _current_date(daten).strftime("%Y-%m-%d")
    product["expires_at"] = _expiry_date(daten, float(product.get("tenor_months", 60))).strftime("%Y-%m-%d")
    product["notional"] = float(product.get("notional", CDS_NOTIONAL))
    product["contract_scale"] = float(product.get("contract_scale", CDS_CONTRACT_SCALE))
    product["contract_size"] = product["notional"] / max(1.0, float(product["contract_scale"]))
    product["recovery_rate"] = float(product.get("recovery_rate", CDS_RECOVERY_RATE))
    product["pricing_note"] = derivative_pricing_note(product)


def _days_to_expiry(daten: ModuleType, product: dict[str, Any]) -> float:
    expires_at = _parse_date(product.get("expires_at"))
    if expires_at is None:
        return max(1.0, float(product.get("tenor_months", 1)) * 30.0)
    return max(1.0, (expires_at - _current_date(daten)).days)


def _expiry_date(daten: ModuleType, tenor_months: float) -> datetime:
    return _current_date(daten) + timedelta(days=round(max(1.0, tenor_months) * 30.0))


def _current_date(daten: ModuleType) -> datetime:
    current = getattr(daten, "datum", None)
    return current if isinstance(current, datetime) else datetime.fromisoformat("1990-01-01")


def _parse_date(value: object) -> datetime | None:
    if isinstance(value, datetime):
        return value
    if not value:
        return None
    try:
        return datetime.fromisoformat(str(value))
    except ValueError:
        return None


def _government_bond_market_yield(daten: ModuleType, country: str, tenor: float) -> float:
    candidates = [
        bond
        for bond in getattr(daten, "bond_market", [])
        if str(bond.get("issuer_type", "")) == "Government"
        and str(bond.get("region", "")) == country
        and float(bond.get("yield_to_maturity", 0.0) or 0.0) > 0.0
    ]
    if not candidates:
        return 0.0
    ranked = sorted(candidates, key=lambda bond: abs(float(bond.get("maturity_years", tenor) or tenor) - tenor))
    nearest = ranked[:3]
    return sum(float(bond.get("yield_to_maturity", 0.0)) for bond in nearest) / len(nearest)


def _market_asset(daten: ModuleType, code: str) -> dict[str, Any]:
    return (
        getattr(daten, "rohstoffe", {}).get(code)
        or getattr(daten, "processed_products", {}).get(code)
        or {}
    )


def _weighted_input_cost(daten: ModuleType, output_code: str) -> float:
    from kojakstreet.core.production_chains import INPUT_RECIPES

    inputs = dict(INPUT_RECIPES.get(output_code, {}))
    if not inputs:
        product = getattr(daten, "processed_products", {}).get(output_code, {})
        raw_inputs = list(product.get("inputs", [])) if isinstance(product, dict) else []
        inputs = {str(code): 1.0 for code in raw_inputs}
    if not inputs:
        return 100.0
    total_weight = sum(float(weight) for weight in inputs.values()) or 1.0
    cost = 0.0
    for code, weight in inputs.items():
        asset = _market_asset(daten, str(code))
        cost += float(asset.get("kurs", 100.0)) * (float(weight) / total_weight)
    return cost


def _currency_strength(daten: ModuleType, region: str) -> float:
    if region == RESERVE_CURRENCY:
        return max(0.0001, float(getattr(daten, "rohstoffe", {}).get("XAU", {}).get("kurs", 100.0)) / 100.0)
    return max(0.0001, float(getattr(daten, "waehrungen_staerke", {}).get(region, 1.0)))


def _country_rate(daten: ModuleType, region: str) -> float:
    if region == RESERVE_CURRENCY:
        return _global_rate(daten)
    return float(getattr(daten, "makro", {}).get(region, {}).get("zins", _global_rate(daten)))


def _expected_inflation(daten: ModuleType, country: str, tenor: float) -> float:
    macro = getattr(daten, "makro", {}).get(country, {})
    current = float(macro.get("inflation", 0.01))
    expected = float(macro.get("expected_inflation", macro.get("expected_cpi", current)))
    global_cpi = float(getattr(daten, "global_macro", {}).get("global_cpi", current))
    return max(-0.03, min(0.25, current * 0.55 + expected * 0.30 + global_cpi * 0.15 + tenor * 0.0008))


def _rating_default_probability(rating: str) -> float:
    table = {
        "AAA": 0.001,
        "AA+": 0.002,
        "AA": 0.003,
        "AA-": 0.004,
        "A+": 0.006,
        "A": 0.008,
        "A-": 0.010,
        "BBB+": 0.014,
        "BBB": 0.020,
        "BBB-": 0.030,
        "BB+": 0.050,
        "BB": 0.075,
        "BB-": 0.100,
        "B+": 0.150,
        "B": 0.220,
        "B-": 0.300,
        "CCC+": 0.400,
        "CCC": 0.520,
        "CCC-": 0.650,
        "CC": 0.780,
        "C": 0.900,
        "D": 1.0,
    }
    return table.get(rating.upper(), 0.02)


def _region_code(region: str) -> str:
    if region == RESERVE_CURRENCY:
        return "GD"
    for country in COUNTRIES:
        if country.name == region:
            return country.code
    return "".join(char for char in str(region).upper() if char.isalpha())[:3] or "REG"


def _currency_label(region: str) -> str:
    return "GD" if region == RESERVE_CURRENCY else _region_code(region)


def _implied_volatility(daten: ModuleType, asset: dict[str, Any], asset_type: str) -> float:
    vix = float(getattr(daten, "global_macro", {}).get("vix", 18.0)) / 100.0
    own_move = abs(float(asset.get("aenderung", 0.0))) / 100.0 * 5.0
    base = 0.18 if asset_type == "Index" else 0.24
    return max(0.08, min(0.95, base + vix * 0.45 + own_move))
